source/bucket/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from bucket.views import home



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^stuff/', include("stuff.urls", namespace="stuff")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/stuff/urls.py
from django.conf.urls import url
from stuff.views import (
    stuff_list,
    stuff_create,
    stuff_update,
    stuff_detail,
    stuff_delete,
)

urlpatterns = [
    url(r'^$', stuff_list, name="list"),
    url(r'^create/$', stuff_create, name="create"),
    url(r'^(?P<id>\d+)/edit/$', stuff_update, name="update"),
    url(r'^(?P<id>\d+)/$', stuff_detail, name="detail"),
    url(r'^(?P<id>\d+)/delete/', stuff_delete, name="delete"),
]

source/stuff/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.db import models

class Container(models.Model):
    title = models.CharField(max_length=25)
    description = models.TextField()
    sortOrder = models.FloatField()
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __unicode__(self): # python 2
        return str(self.title)

    def __str__(self): # python 3
        return str(self.title)



class Category(models.Model):
    title = models.CharField(max_length=25)
    description = models.TextField()
    sortOrder = models.FloatField()
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __unicode__(self): # python 2
        return str(self.title)

    def __str__(self): # python 3
        return str(self.title)

    class Meta:
        verbose_name_plural = "Categories"

class Item(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    category = models.ForeignKey(Category)
    location = models.CharField(max_length=25)
    container = models.ForeignKey(Container, default=1)
    description = models.CharField(max_length=100)
    unit = models.CharField(max_length=25)
    qty = models.IntegerField()
    purchaseDate = models.DateTimeField(blank=True)
    bestByDate = models.DateTimeField(blank=True)
    checkOnFrequency = models.CharField(max_length=25, blank=True)
    moreInfoLink = models.CharField(max_length=100, blank=True)
    waterStored = models.FloatField(blank=True, null=True)
    numServings = models.IntegerField(blank=True, null=True)
    calPerServing = models.IntegerField(blank=True, null=True)
    prescriptionMed = models.BooleanField(blank=True)
    notes = models.TextField(blank=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __unicode__(self): # python 2
        return str(self.id)

    def __str__(self): # python 3
        return str(self.id)

source/stuff/forms.py
from django import forms

from stuff.models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'category',
            'location',
            'container',
            'description',
            'unit',
            'qty',
            'purchaseDate',
            'bestByDate',
            'checkOnFrequency',
            'moreInfoLink',
            'waterStored',
            'numServings',
            'calPerServing',
            'prescriptionMed',
            'notes',
        ]

source/bucket/views.py
from django.shortcuts import render

def home(request):
    context = {
        "title": "Home"
    }
    return render(request, "home.html", context)

source/stuff/views.py
from django.shortcuts import render

from stuff.forms import ItemForm
from stuff.models import Item

def stuff_list(request):
    context = {
        "title": "list"
    }
    return render(request, "stuff_list.html", context)

def stuff_create(request):
    if not request.user.is_authenticated:
        raise Http404

    form = ItemForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": "Add New Stuff",
        "form": form,
    }
    return render(request, "stuff_form.html", context)


def stuff_update(request, id=None):
    context = {
        "title": "update"
    }
    return render(request, "stuff_form.html", context)

def stuff_detail(request, id=None):
    context = {
        "title": "detail"
    }
    return render(request, "stuff_detail.html", context)

def stuff_delete(request, id=None):
    context = {
        "title": "delete"
    }
    return render(request, "home.html", context)

source/templates/_css.html
{% load staticfiles%}

<!-- Bootstrap 3.3.7 minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Font-Awesome 4.6 minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Custom CSS -->
<link href="{% static 'css/custom.css' %}" rel="stylesheet" >

source/templates/_js.html
{% load staticfiles%}

<!-- JavaScript Links -->
<!-- jquery 1.12.4 minified JS -->
<script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>

<!-- Bootstrap 3.3.7 minified JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<!-- IE10 viewport hack for Surface/desktop Windows 8 bug - ->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script> -->

<!-- Custom JavaScript - ->
<script src="{% static 'js/custom.js' %}"></script> -->

source/templates/_messages.html
{% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

source/templates/_navbar.html
{% load staticfiles%}

<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="#"><img class="logo_nav"  src="{% static 'img/logoBlack_sm.png' %}" /></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="welcome_User">Welcome {{ request.user.username }}</li>
                    <li><a href="/profiles/{{ user.username }}/ ">Profile</a></li>
                    <li><a href="/accounts/logout/ ">Logout</a></li>
                {% else %}
                    <li><a href="/accounts/login/">Login</a></li>
                    <li><a href="/accounts/signup/">Sign Up</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

source/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" href="{% static 'img/favicon.ico' %}" />

    <title>myStuff</title>

    {% include '_css.html' %}

</head>
<body>

    {% include "_messages.html" %}

    <div class="container">

        {% include '_navbar.html' %}

        {% block jumbotron %}
        {% endblock %}

        {% block content %}
        {% endblock %}


    </div> <!-- /container -->

    {% include '_js.html' %}

</body>
</html>

source/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block jumbotron %}
<div class="jumbotron">
    <p class="center">
        <img class="logo_jumbotron" src="{% static 'img/logoBlack.png' %}" />
    </p>
    <p>Keep track of all your stuff</p>
</div>
{% endblock %}

source/templates/stuff_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <h1>{{ title }}</h1>
{% endblock %}

source/templates/stuff_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<br>
<div class="col-sm-6 col-sm-offset-3">
    <h1>{{ title }}</h1>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <!--{% if 'create' in request.build_absolute_uri %}
            <input type="submit" class="btn btn-success" value="Create Post">
        {% else %}
            <input type="submit" class="btn btn-success" value="Update Post">
        {% endif %}-->
        <input type="submit" class="btn btn-success" value="Submit">
        &nbsp;
        <a href='{% url "stuff:list" %}' class="btn btn-success" role="button">cancel</a>
    </form>
</div>

{% endblock %}

source/templates/stuff_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <h1>{{ title }}</h1>
{% endblock %}